// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SUMAPT.Infrastructure.Persistence;

#nullable disable

namespace SUMAPT.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.HistorialNota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EstadoCurso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("InscripcionId")
                        .HasColumnType("uuid");

                    b.Property<short>("Intentos")
                        .HasColumnType("smallint");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("NotaFinal")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("RegistradoPor");

                    b.ToTable("historial_notas", "academico");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.Inscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("ProgramaId");

                    b.HasIndex("EstudianteId", "ProgramaId", "PeriodoId")
                        .IsUnique();

                    b.ToTable("inscripciones", "academico");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.Institucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DominioEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NombreCorto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("NombreCorto")
                        .IsUnique();

                    b.ToTable("instituciones", "academico");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.Materia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Creditos")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<short?>("PeriodoSugerido")
                        .HasColumnType("smallint");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaId", "Codigo")
                        .IsUnique();

                    b.ToTable("materias", "academico");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.ModeloAcademico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PeriodosPorAño")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.ToTable("modelos_academicos", "academico");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.Periodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.ToTable("periodos", "academico");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.Programa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracionPeriodos")
                        .HasColumnType("integer");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeloId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("ModeloId");

                    b.ToTable("programas", "academico");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Analitica.EventoTelemetria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntidadTipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SesionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "RegistradoEn")
                        .IsDescending(false, true);

                    b.ToTable("eventos_telemetria", "analitica");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Analitica.MetricaAgregada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CalculadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PeriodoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoMetrica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.ToTable("metricas_agregadas", "analitica");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Analitica.PrediccionRiesgo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Factores")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("GeneradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InscripcionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ScoreRiesgo")
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("VersionModelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("VigenteHasta")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionId", "GeneradoEn")
                        .IsDescending(false, true);

                    b.ToTable("predicciones_riesgo", "analitica", t =>
                        {
                            t.HasCheckConstraint("CK_Score_Rango", "\"ScoreRiesgo\" >= 0 AND \"ScoreRiesgo\" <= 1");
                        });
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Auditoria.LogAccion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("jsonb");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("jsonb");

                    b.Property<string>("DetalleError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EjecutadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntidadId")
                        .HasColumnType("text");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RolActivo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntidadTipo", "EntidadId");

                    b.HasIndex("UsuarioId", "EjecutadoEn")
                        .IsDescending(false, true);

                    b.ToTable("log_acciones", "auditoria");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Auth.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", "auth");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Auth.Sesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ExpiradaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IniciadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("KeycloakSid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakSid")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .HasFilter("\"Activa\" = TRUE");

                    b.ToTable("sesiones", "auth");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Auth.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("KeycloakId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UltimoAccesoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KeycloakId")
                        .IsUnique();

                    b.ToTable("usuarios", "auth");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Auth.UsuarioRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AsignadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AsignadoPorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InstitucionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId", "InstitucionId")
                        .IsUnique();

                    b.ToTable("usuario_roles", "auth");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Comunicacion.Conversacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipanteA")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipanteB")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteB");

                    b.HasIndex("ParticipanteA", "ParticipanteB")
                        .IsUnique();

                    b.ToTable("conversaciones", "comunicacion", t =>
                        {
                            t.HasCheckConstraint("CK_Conversacion_Distintos", "\"ParticipanteA\" <> \"ParticipanteB\"");
                        });
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Comunicacion.Mensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EnviadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LeidoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RemitenteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RemitenteId");

                    b.HasIndex("ConversacionId", "EnviadoEn")
                        .IsDescending(false, true);

                    b.ToTable("mensajes", "comunicacion");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Comunicacion.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatosExtra")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LeidaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId")
                        .HasFilter("\"Leida\" = FALSE");

                    b.ToTable("notificaciones", "comunicacion");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Mentoria.ActaSesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Compromisos")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NivelRiesgoPercibido")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("TemasTratados")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.ToTable("actas_sesion", "mentoria");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Mentoria.Cita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CanceladoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnlaceVirtual")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaHoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaHoraIni")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InscripcionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MotivoCancel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("MentorId");

                    b.ToTable("citas", "mentoria", t =>
                        {
                            t.HasCheckConstraint("CK_Cita_Fechas", "\"FechaHoraFin\" > \"FechaHoraIni\"");
                        });
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Mentoria.Disponibilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<short>("DiaSemana")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("disponibilidad", "mentoria", t =>
                        {
                            t.HasCheckConstraint("CK_Disponibilidad_Horas", "\"HoraFin\" > \"HoraInicio\"");
                        });
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Mentoria.PerfilMentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Biografia")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Especialidades")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<short>("MaxEstudiantes")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("perfiles_mentor", "mentoria");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.HistorialNota", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Academico.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SUMAPT.Domain.Entities.Academico.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SUMAPT.Domain.Entities.Academico.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SUMAPT.Domain.Entities.Auth.Usuario", "Auditor")
                        .WithMany()
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Auditor");

                    b.Navigation("Inscripcion");

                    b.Navigation("Materia");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.Inscripcion", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Auth.Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SUMAPT.Domain.Entities.Academico.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SUMAPT.Domain.Entities.Academico.Programa", "Programa")
                        .WithMany()
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Periodo");

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.Materia", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Academico.Programa", "Programa")
                        .WithMany()
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.ModeloAcademico", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Academico.Institucion", "Institucion")
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.Periodo", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Academico.Institucion", "Institucion")
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Academico.Programa", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Academico.Institucion", "Institucion")
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SUMAPT.Domain.Entities.Academico.ModeloAcademico", "ModeloAcademico")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institucion");

                    b.Navigation("ModeloAcademico");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Analitica.MetricaAgregada", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Academico.Institucion", "Institucion")
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Analitica.PrediccionRiesgo", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Academico.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Auth.Sesion", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Auth.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Auth.UsuarioRol", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Auth.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SUMAPT.Domain.Entities.Auth.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Comunicacion.Conversacion", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Auth.Usuario", "UsuarioA")
                        .WithMany()
                        .HasForeignKey("ParticipanteA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SUMAPT.Domain.Entities.Auth.Usuario", "UsuarioB")
                        .WithMany()
                        .HasForeignKey("ParticipanteB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioA");

                    b.Navigation("UsuarioB");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Comunicacion.Mensaje", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Comunicacion.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SUMAPT.Domain.Entities.Auth.Usuario", "Remitente")
                        .WithMany()
                        .HasForeignKey("RemitenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversacion");

                    b.Navigation("Remitente");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Comunicacion.Notificacion", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Auth.Usuario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinatario");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Mentoria.ActaSesion", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Mentoria.Cita", "Cita")
                        .WithOne()
                        .HasForeignKey("SUMAPT.Domain.Entities.Mentoria.ActaSesion", "CitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Mentoria.Cita", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Auth.Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SUMAPT.Domain.Entities.Academico.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SUMAPT.Domain.Entities.Mentoria.PerfilMentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Inscripcion");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Mentoria.Disponibilidad", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Mentoria.PerfilMentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("SUMAPT.Domain.Entities.Mentoria.PerfilMentor", b =>
                {
                    b.HasOne("SUMAPT.Domain.Entities.Auth.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("SUMAPT.Domain.Entities.Mentoria.PerfilMentor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
